language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install --upgrade pip  --use-mirrors
  - pip install coveralls pytest pytest-cov pytest-pep8 pep257 --use-mirrors
  - pip install -e .[docs]

script:
  - sh run_tests.sh

after_success:
  - coveralls

notifications:
  email: false
