language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install --upgrade pip  --use-mirrors
  - pip install coveralls pytest pytest-cov pytest-pep8 --use-mirrors
  - pip install .

script:
  - py.test --clearcache --pep8 --doctest-modules --cov=dictdiffer.py dictdiffer.py tests.py

after_success:
  - coveralls

notifications:
  email: false
